FROM x7
USER user
WORKDIR /grapheneos

ARG PIXEL_CODENAME=bluejay
ARG BUILD_TARGET=user
#ARG BUILD_TARGET=userdebug

#NOTE Here is some documentation on how the mount with type=cache works:
# https://github.com/moby/buildkit/issues/1673#issuecomment-1264502398
# tl;dr: caches with same id will be shared between all DockerFiles,
#        data will be in ~/data2/gos-docker/buildkit in some form,
#        cache can vanish at any time due to GC

RUN rm -rf out

#RUN /tools/yarn/node_modules/.bin/yarn --cwd vendor/adevtool/
RUN --mount=type=bind,source=yarn-adevtool.sh,target=/tmp/yarn-adevtool.sh \
  --mount=type=cache,id=yarn-pkgs,target=/cache/yarn-pkgs,uid=1000,sharing=locked \
  /tmp/yarn-adevtool.sh

RUN bash -c "source build/envsetup.sh && m aapt2"

# This needs `eval` because the alias for adevtool is defined by envsetup.
RUN --mount=type=cache,id=adevtool-dl,target=/grapheneos/vendor/adevtool/dl,uid=1000,sharing=locked \
  --network=none \
  bash -O expand_aliases -c "source build/envsetup.sh && eval adevtool generate-all -d $PIXEL_CODENAME"

ENV OFFICIAL_BUILD=true
RUN --network=none \
  bash -O expand_aliases -c "source build/envsetup.sh && eval lunch ${PIXEL_CODENAME}-${BUILD_TARGET}"

RUN --network=none bash -O expand_aliases -c "source build/envsetup.sh && eval m vendorbootimage"
RUN --network=none bash -O expand_aliases -c "source build/envsetup.sh && eval m target-files-package"

