#FROM docker.io/library/ubuntu:22.04
FROM docker.io/library/ubuntu@sha256:e6173d4dc55e76b87c4af8db8821b1feae4146dd47341e4d431118c7dd060a74

# add few dependencies here so we have less reason to run that `repo sync` again (which would mean from scratch)
RUN apt update && apt install -y \
  repo python3 git gnupg

#RUN adduser user --disabled-password </dev/null
# -> might trigger a bug, see https://docs.docker.com/develop/develop-images/instructions/#user
RUN useradd --no-log-init --create-home user
RUN install -o user -g user -m 700 -d /grapheneos
WORKDIR /grapheneos
USER user

#ARG TAG_NAME=14  # without "refs/tags/" because it is a branch
ARG TAG_NAME=refs/tags/2024012600
RUN repo init -u https://github.com/GrapheneOS/platform_manifest.git -b $TAG_NAME


#ADD https://grapheneos.org/allowed_signers /home/user/.ssh/grapheneos_allowed_signers
# don't make it persistent because we won't copy $HOME from this image
RUN --mount=type=bind,src=grapheneos_allowed_signers,dst=/tmp/grapheneos_allowed_signers \
  cd .repo/manifests && git -c gpg.ssh.allowedSignersFile=/tmp/grapheneos_allowed_signers verify-tag $(git describe)

# "|| true" is so we don't loose progress if it fails
#RUN repo sync -j8 || true
RUN repo sync -j8 --retry-fetches=3 --force-sync --network-only || true

LABEL gos="src-initial"

