FROM x7
USER user
WORKDIR /grapheneos

ARG PIXEL_CODENAME=bluejay
ARG BUILD_TARGET=user
#ARG BUILD_TARGET=userdebug

#NOTE Here is some documentation on how the mount with type=cache works:
# https://github.com/moby/buildkit/issues/1673#issuecomment-1264502398
# tl;dr: caches with same id will be shared between all DockerFiles,
#        data will be in ~/data2/gos-docker/buildkit in some form,
#        cache can vanish at any time due to GC

RUN rm -rf out

#RUN /tools/yarn/node_modules/.bin/yarn --cwd vendor/adevtool/
RUN --mount=type=bind,source=yarn-adevtool.sh,target=/tmp/yarn-adevtool.sh \
  --mount=type=cache,id=yarn-pkgs,target=/cache/yarn-pkgs,uid=1000,sharing=locked \
  /tmp/yarn-adevtool.sh

RUN bash -c "source build/envsetup.sh && m aapt2"

# This needs `eval` because the alias for adevtool is defined by envsetup.
RUN --mount=type=cache,id=adevtool-dl,target=/grapheneos/vendor/adevtool/dl,uid=1000,sharing=locked \
  --network=none \
  bash -O expand_aliases -c "source build/envsetup.sh && eval adevtool generate-all -d $PIXEL_CODENAME"

ENV OFFICIAL_BUILD=true
RUN --network=none \
  bash -O expand_aliases -c "source build/envsetup.sh && eval lunch ${PIXEL_CODENAME}-${BUILD_TARGET}"

RUN rm -f done-vendorbootimage done-target-files-package
RUN --network=none bash -O expand_aliases -c "source build/envsetup.sh && eval m vendorbootimage" \
  && touch done-vendorbootimage || echo "step failed but don't tell BuildKit, yet"
# If the previous step has failed, BuildKit will see the error here. Restart with `--invoke=on-error`
# and you should immediately fall into a shell for this step (because the previous one was "successfull"
# and has thus been cached). We allow network in here because that can be useful in the debug shell.
RUN [ -e done-vendorbootimage ]

RUN --network=none bash -O expand_aliases -c "source build/envsetup.sh && eval m target-files-package" \
  && touch done-target-files-package || echo "step failed but don't tell BuildKit, yet"
RUN [ -e done-target-files-package ]

